SQMAGOPC-281 Added deprecated messages
OPMerchantServices/op-payment-service-for-magento-2 pull request #165
Opened 2021-10-27 11:51 UTC by richard-madarasz

- Replaced version check messages with deprecated message and link to new repository
- Added deprecated note to the top of readme
- added abandoned to composer
- changed version number to 1.3.4

2021-10-28 08:08 UTC, Seppo-Konttinen-Solteq submitted a review, later dismissed

2021-10-28 08:08 UTC, Seppo-Konttinen-Solteq commented on composer.json
> +  "abandoned": "paytrail/paytrail-for-adobe-commerce"
Should here be the OP module not Paytrail? Or how the syntax goes here

2021-10-28 08:11 UTC, richard-madarasz commented on composer.json
> +  "abandoned": "paytrail/paytrail-for-adobe-commerce"
Schema is that it can be boolean or a package name/URL pointing to a recommended alternative. https://getcomposer.org/doc/04-schema.md#abandoned

2021-11-17 12:04 UTC, loueranta-paytrail requested changes

2021-11-17 12:04 UTC, loueranta-paytrail commented on README.md
> +Checkout’s Extranet.</b><br/>
Should be "Paytrail's Extranet"

2021-11-17 12:04 UTC, loueranta-paytrail commented on README.md
> +<b>Please note that the module configurations will not carry over from Checkout Finland to Paytrail for Adobe Commerce! You will need to save these values and reapply them yourself. This also applies
I think we should add some mention about CSS class name changes as well

2021-11-17 13:05 UTC, loueranta-paytrail approved these changes

2021-11-18 09:25 UTC, merged